=== kunalshah017/Learning-Csharp/ASP.NET/Practical Programs/10-03-2025/book.dtd
<!-- External DTD for books -->
<!ELEMENT Books (Book+)>
<!ELEMENT Book (name, author, price)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)> 
<!ELEMENT price (#PCDATA)>

=== kunalshah017/Learning-Csharp/ASP.NET/Practical Programs/10-03-2025/external-dtd-book.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- External DTD for books -->
<!DOCTYPE Books SYSTEM "book.dtd">

<Books>
  <Book>
    <name>The C# Programming Language</name>
    <author>Ian Griffiths</author>
    <price>39.95</price>
  </Book>
  <Book>
    <name>C# in Depth</name>
    <author>Jon Skeet</author>    
    <price>39.95</price>
  </Book>
  <Book>
    <name>C# 2008 in a Nutshell</name>
    <author>Jeffrey Richter</author>  
    <price>39.95</price>
  </Book>
</Books>
