<?xml version="1.0" encoding="utf-8"?>

<!-- Internal DTD for books -->
<!DOCTYPE Books [
  <!ELEMENT Books (Book+)>
  <!ELEMENT Book (name, author, price)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
]>

<Books>
  <Book>
    <name>The C# Programming Language</name>
    <author>Ian Griffiths</author>
    <price>39.95</price>
  </Book>
  <Book>
    <name>C# in Depth</name>
    <author>Jon Skeet</author>    
    <price>39.95</price>
  </Book>
  <Book>
    <name>C# 2008 in a Nutshell</name>
    <author>Jeffrey Richter</author>  
    <price>39.95</price>
  </Book>
</Books>
